# syntax=docker/dockerfile:experimental
#https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066

FROM node:8-alpine

ENV DATABASE_URL 'postgres://postgres/open-wedding'

#pull git code or Copy from local filesystem
#COPY ./*
RUN npm install -g grunt-cli


RUN npm install
